"""opening hours and one shift per day

Revision ID: 03d3d0f66a41
Revises: fae8f9d05fbf
Create Date: 2026-08-25 09:10:21.366054

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "03d3d0f66a41"
down_revision: str | Sequence[str] | None = "fae8f9d05fbf"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


HOURS_PAIR = (
    "(opens IS NULL AND closes IS NULL)"
    " OR (opens IS NOT NULL AND closes IS NOT NULL AND closes > opens)"
)


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "opening_hours",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("weekday", sa.Integer(), nullable=False),
        sa.Column("opens", sa.Time(), nullable=True),
        sa.Column("closes", sa.Time(), nullable=True),
        sa.CheckConstraint(HOURS_PAIR, name="ck_opening_hours_pair"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("weekday", name="uq_opening_hours_weekday"),
    )
    op.create_table(
        "schedule_opening_hours",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("schedule_id", sa.Integer(), nullable=False),
        sa.Column("weekday", sa.Integer(), nullable=False),
        sa.Column("opens", sa.Time(), nullable=True),
        sa.Column("closes", sa.Time(), nullable=True),
        sa.CheckConstraint(HOURS_PAIR, name="ck_schedule_opening_hours_pair"),
        sa.ForeignKeyConstraint(["schedule_id"], ["schedules.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("schedule_id", "weekday", name="uq_schedule_opening_hours_day"),
    )
    with op.batch_alter_table("schedule_opening_hours", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_schedule_opening_hours_schedule_id"), ["schedule_id"], unique=False
        )

    with op.batch_alter_table("shifts", schema=None) as batch_op:
        batch_op.create_index(
            "uq_shifts_one_per_day", ["schedule_employee_id", "shift_date"], unique=True
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("shifts", schema=None) as batch_op:
        batch_op.drop_index("uq_shifts_one_per_day")

    with op.batch_alter_table("schedule_opening_hours", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_schedule_opening_hours_schedule_id"))

    op.drop_table("schedule_opening_hours")
    op.drop_table("opening_hours")
    # ### end Alembic commands ###
