"""per date opening hours overrides

Revision ID: 9a09ec6b9dec
Revises: 03d3d0f66a41
Create Date: 2026-08-25 10:32:32.577742

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9a09ec6b9dec"
down_revision: str | Sequence[str] | None = "03d3d0f66a41"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


HOURS_PAIR = (
    "(opens IS NULL AND closes IS NULL)"
    " OR (opens IS NOT NULL AND closes IS NOT NULL AND closes > opens)"
)


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "schedule_day_overrides",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("schedule_id", sa.Integer(), nullable=False),
        sa.Column("day", sa.Date(), nullable=False),
        sa.Column("opens", sa.Time(), nullable=True),
        sa.Column("closes", sa.Time(), nullable=True),
        sa.CheckConstraint(HOURS_PAIR, name="ck_schedule_day_overrides_pair"),
        sa.ForeignKeyConstraint(["schedule_id"], ["schedules.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("schedule_id", "day", name="uq_schedule_day_overrides_day"),
    )
    with op.batch_alter_table("schedule_day_overrides", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_schedule_day_overrides_schedule_id"), ["schedule_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("schedule_day_overrides", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_schedule_day_overrides_schedule_id"))

    op.drop_table("schedule_day_overrides")
    # ### end Alembic commands ###
