"""core schema

Revision ID: fae8f9d05fbf
Revises:
Create Date: 2026-08-09 18:40:41.455369

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "fae8f9d05fbf"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "employees",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("first_name", sa.String(length=80), nullable=False),
        sa.Column("last_name", sa.String(length=80), nullable=False),
        sa.Column(
            "profession",
            sa.Enum("PHARMACIST", "TECHNICIAN", name="profession", create_constraint=True),
            nullable=False,
        ),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "schedules",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("end_date", sa.Date(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("DRAFT", "FINAL", "ARCHIVED", name="schedule_status", create_constraint=True),
            nullable=False,
        ),
        sa.Column("finalized_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint("end_date >= start_date", name="ck_schedules_dates_ordered"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "schedule_employees",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("schedule_id", sa.Integer(), nullable=False),
        sa.Column("employee_id", sa.Integer(), nullable=False),
        sa.Column("display_order", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["employee_id"], ["employees.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["schedule_id"], ["schedules.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("schedule_id", "employee_id", name="uq_schedule_employees_pair"),
    )
    with op.batch_alter_table("schedule_employees", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_schedule_employees_employee_id"), ["employee_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_schedule_employees_schedule_id"), ["schedule_id"], unique=False
        )

    op.create_table(
        "shifts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("schedule_employee_id", sa.Integer(), nullable=False),
        sa.Column("shift_date", sa.Date(), nullable=False),
        sa.Column("start_time", sa.Time(), nullable=False),
        sa.Column("end_time", sa.Time(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint("end_time > start_time", name="ck_shifts_times_ordered"),
        sa.ForeignKeyConstraint(
            ["schedule_employee_id"], ["schedule_employees.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("shifts", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_shifts_schedule_employee_id"), ["schedule_employee_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_shifts_shift_date"), ["shift_date"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("shifts", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_shifts_shift_date"))
        batch_op.drop_index(batch_op.f("ix_shifts_schedule_employee_id"))

    op.drop_table("shifts")
    with op.batch_alter_table("schedule_employees", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_schedule_employees_schedule_id"))
        batch_op.drop_index(batch_op.f("ix_schedule_employees_employee_id"))

    op.drop_table("schedule_employees")
    op.drop_table("schedules")
    op.drop_table("employees")
    # ### end Alembic commands ###
